language: java


jdk:
- oraclejdk6


env:
- TERM=dumb


build:
  - cd VRL-NeuGen-Plugin/
  - ./gradlew clean build


after_success:
- ./gradlew jacocoTestReport coveralls


notifications:
  email:
    - stephan@syntaktischer-zucker.de
  on_success: always
  on_failure: always
